apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: edu-user
data:
  .dockerconfigjson: >
    eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsic2VydmVybmFtZSI6Imh0dHBzOi8vaW5kZXguZG9ja....==
type: kubernetes.io/dockerconfigjson